# Generated by Django 4.0.5 on 2022-07-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('Student_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('Sponsor_email', models.CharField(max_length=50)),
                ('Sponsor_No', models.CharField(default=234, max_length=15)),
                ('Sponsor_location', models.CharField(max_length=255)),
                ('Full_name', models.CharField(max_length=255)),
                ('Debt', models.CharField(max_length=50)),
                ('Student_class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Body', models.TextField(help_text='Enter help here')),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=50)),
                ('State', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Local_Government', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('School_owner', models.CharField(max_length=255)),
                ('School_name', models.CharField(max_length=255)),
                ('Reg_number', models.CharField(max_length=255)),
                ('Locality', models.CharField(max_length=255)),
                ('Debtor', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Email', models.CharField(help_text='Enter valid email', max_length=255)),
                ('Password', models.CharField(help_text='Enter valid password', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='School_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pics', models.ImageField(upload_to='')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Debtor.school')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_created=True)),
                ('Title', models.CharField(max_length=255)),
                ('Body', models.TextField(help_text='Enter post here...')),
                ('Deptors', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Debtor.school')),
            ],
        ),
        migrations.CreateModel(
            name='Deptors_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile_pics', models.ImageField(upload_to='')),
                ('Deptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Debtor.debtor')),
            ],
        ),
        migrations.CreateModel(
            name='Contend',
            fields=[
                ('Email', models.CharField(max_length=50)),
                ('Student_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('How_to_be_contacted', models.CharField(help_text='specify email or phone number', max_length=255)),
                ('Complain', models.TextField(help_text='Enter your complain here...')),
                ('School', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Debtor.school')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_created=True)),
                ('Body', models.TextField(help_text='Enter your comments here...')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Debtor.post')),
            ],
        ),
    ]
