# Generated by Django 4.0.5 on 2022-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated']},
        ),
        migrations.RenameField(
            model_name='school',
            old_name='school_id',
            new_name='School_id',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debt',
            field=models.IntegerField(max_length=50),
        ),
    ]
