# Generated by Django 4.0 on 2022-08-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='debtor',
            field=models.ManyToManyField(blank=True, to='Debtor.Debtor'),
        ),
    ]
