# Generated by Django 4.0.5 on 2022-08-07 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0002_alter_post_options_rename_school_id_school_school_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debt',
            field=models.IntegerField(),
        ),
    ]
