# Generated by Django 4.0.5 on 2022-08-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0004_debtor_debtor_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='student_class',
            field=models.CharField(max_length=50),
        ),
    ]
