# Generated by Django 4.0.5 on 2022-08-07 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0006_remove_debtor_full_name_alter_deptors_profile_debtor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
    ]
