# Generated by Django 4.1 on 2022-08-08 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0007_delete_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debtor',
            name='debtor_image',
        ),
    ]
