# Generated by Django 4.1 on 2022-08-08 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0008_remove_debtor_debtor_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='debtor_image',
            field=models.ImageField(null=True, upload_to='debtors pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='deptors_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Debtor.debtor'),
        ),
        migrations.DeleteModel(
            name='Deptors_profile',
        ),
    ]
