# Generated by Django 4.1 on 2022-08-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0013_meeting_metting_comment_reply_metting_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtor',
            name='debtor_image',
            field=models.ImageField(default='fixed.jpeg', null=True, upload_to='debtors pics'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_profile_image',
            field=models.ImageField(default='fixed.jpeg', upload_to='Meeting DP'),
        ),
    ]
