# Generated by Django 4.1 on 2022-08-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0014_alter_debtor_debtor_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metting_comment',
            name='body',
            field=models.CharField(max_length=1000000000000000000),
        ),
    ]
