# Generated by Django 4.1 on 2022-08-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0015_alter_metting_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metting_comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MettingCommentImage'),
        ),
    ]
