# Generated by Django 4.1 on 2022-08-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0016_alter_metting_comment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metting_comment_reply',
            name='body',
            field=models.CharField(max_length=100000000000000),
        ),
    ]
