# Generated by Django 4.1 on 2022-08-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0017_alter_metting_comment_reply_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metting_Comment_Reply',
            new_name='MettingCommentReply',
        ),
    ]
