# Generated by Django 4.1 on 2022-08-10 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0018_rename_metting_comment_reply_mettingcommentreply'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MettingCommentReply',
            new_name='Metting_Comment_Reply',
        ),
        migrations.AlterField(
            model_name='metting_comment_reply',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Debtor.metting_comment'),
        ),
    ]
