# Generated by Django 4.1 on 2022-08-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0019_rename_mettingcommentreply_metting_comment_reply_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Metting_Comment',
            new_name='Meeting_Comment',
        ),
        migrations.RenameModel(
            old_name='Metting_Comment_Reply',
            new_name='Meeting_Comment_Reply',
        ),
    ]
