# Generated by Django 4.1 on 2022-08-10 22:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0020_rename_metting_comment_meeting_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='meeting_profile_image',
            field=models.ImageField(default='fixed.jpg', upload_to='Meeting DP'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='Main', to=settings.AUTH_USER_MODEL),
        ),
    ]
