# Generated by Django 4.0.5 on 2022-08-11 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0021_alter_meeting_meeting_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='debtor',
            options={'ordering': ['-updated']},
        ),
        migrations.RemoveField(
            model_name='school_profile',
            name='debtor',
        ),
        migrations.AlterField(
            model_name='debtor',
            name='debtor_image',
            field=models.ImageField(default='fixed.jpg', null=True, upload_to='debtors pics'),
        ),
    ]
