# Generated by Django 4.0.5 on 2022-08-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0022_alter_debtor_options_remove_school_profile_debtor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Founded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Number_of_students',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Number_of_teachers',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Permanent_address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Phone_numnber',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Registered_session',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='current_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
