# Generated by Django 4.0.5 on 2022-08-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0024_school_profile_school_owner_pics'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Session',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='Founded',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
