# Generated by Django 4.0.5 on 2022-08-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0027_remove_school_info_two_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='body',
            field=models.TextField(),
        ),
    ]
