# Generated by Django 4.0.5 on 2022-08-13 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Debtor', '0028_alter_help_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='Phone_number',
            new_name='Contact_number',
        ),
    ]
